version: '3'
services: 

  mysql:
    image: mysql:8.0.17
    cap_add: 
      - SYS_NICE
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    ports: 
      - "3307:3307"
    volumes: 
      - ./data/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql